spring.application.name=AccountBook

#dataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/account_book?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=ssafy
spring.datasource.password=ssafy

#mybtais
#mappers
#mybatis.mapper-locations=classpath:mappers/boardMapper.xml
mybatis.mapper-locations=classpath:mappers/*.xml

#type as

mybatis.type-aliases-package=com.ssafy.user.entity,com.ssafy.user.dto.request,com.ssafy.user.dto.response, com.ssafy.community,com.ssafy.book.entity, com.ssafy.comment, com.ssafy.challenge

mybatis.configuration.map-underscore-to-camel-case=true

openai.api.key=S14P02AO09-fb948232-21b7-43f5-afb0-e08895cdc3d0
gms.api.key=S14P02AO09-fb948232-21b7-43f5-afb0-e08895cdc3d0
